print("Mad libs where libs get Mad\n Start Below:\n")
time=input("Number: ")
item=input("Noun(plural): ")
name=input("Name: ")
scream=input("Any sentenve: ")
action=input("Verb: ")
print("\n")
print("It was" , time , "o'clock when I heard a knock at the door.\nI opened the door and there was a box full of" , item , "with a note saying \"From Mr.", name.title() , "\"")
print("Just as I closed the door I heard a scream \"",scream.upper(),"\"\nI froze in place and all I could do was" , action)
